version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env   # 👈 This loads environment variables from .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


