


version: '3'
services:
  app:
    image: mashahir/quotly_server:server-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


